services:
  server:
    build: ./server
    command: npm start
    ports: 
      - 3333:3333
    volumes:
      - .:/usr/server
  client:
    build: ./app
    command: yarn dev
    ports: 
      - 3000:3000
    volumes:
      - .:/usr/app